### PR TITLE
Adds mobile menus! changes

### PR DESCRIPTION
**Pull request by timurtripp**
- Expands all main menu child menu items. (CuBoulder/tiamat-theme#647)

CuBoulder/tiamat-theme#653

Sister PR in: [tiamat-theme](https://github.com/CuBoulder/tiamat-theme/pull/660)

### CODE REVIEW

**Comment by jcsparks** [comment]
Functionality looks great.  If we're going to style the hamburger menu, we should make it look like the current live sites.  It doesn't need to take up a full row of content on a display that's already space limited.  Let's move it in at the end of the site header and toggle to the X icon to close like they have now.  

Otherwise looks great.  I still think they're going to want to revert these changes once they see them (aside from the updated styling) and if they don't we'll have to figure out how to handle the sidebar as that becomes duplicate content in this solution.  But lets hold off until the UI/UX team makes a call on the main menu mobile functionality first.  

Thanks @timurtripp

**Review by jcsparks — CHANGES_REQUESTED** [review]
See comment

**Comment by timurtripp** [comment]
I put it at the end of the brand bar instead of the end of the header, didn't I. It has been a long week...

**Comment by timurtripp** [comment]
In the correct place now

**Review by jcsparks — APPROVED** [review]

**Pull request merged**
