### PR TITLE
Update administer content permission

### LINKED ISSUE #59: Permissions for changing author, publish date
Looks like we need to extend the Administer Content permission to roles that can create content since it prevents access to changing author or the publish date:

image

### PR DESCRIPTION
**Pull request by jacob-korf**
Adds the administer content permission to all 4 main roles.

Resolves CuBoulder/tiamat10-profile#59
Resolves CuBoulder/tiamat10-profile#94

### CODE REVIEW

**Comment by jacob-korf** [comment]
Also closes #92.

**Comment by timurtripp** [comment]
You have to edit the OP for it to properly link, not add a comment. Click the three dots → Edit. I did so for this one.

**Comment by timurtripp** [comment]
If done correctly you'll see that icon to the left of your avatar
Screenshot 2024-02-28 at 11 09 12 AM

**Comment by timurtripp** [comment]
And also on the right sidebar of the page here.

**Review by jcsparks — APPROVED** [review]

**Pull request merged**
